version: "3"
services:
  app:
    build: .
    container_name: nodejs-container
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    image: 'mongo'
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
